### PR TITLE
Implement the farp plugin on macos

### PR DESCRIPTION
**Pull request by sddj**

### CODE REVIEW

**Comment by tobiasbrunner** [comment]
Interesting. Please see [Contributions](https://wiki.strongswan.org/projects/strongswan/wiki/Contributions) and [ProgrammingStyle](https://wiki.strongswan.org/projects/strongswan/wiki/ProgrammingStyle) on our wiki.

Also, is that macOS only or would that BPF approach also work on FreeBSD?

**Comment by sddj** [comment]
> Interesting. Please see [Contributions](https://wiki.strongswan.org/projects/strongswan/wiki/Contributions) and [ProgrammingStyle](https://wiki.strongswan.org/projects/strongswan/wiki/ProgrammingStyle) on our wiki.
> 
> Also, is that macOS only or would that BPF approach also work on FreeBSD?

Updated based on Contributions and ProgrammingStyle.  I still need to look into FreeBSD.

**Comment by tobiasbrunner** [comment]
Great, thanks.

I've squashed your commits together and pushed them along with several refactorings and fixups to the _gh189-farp-bpf_ branch. It compiles on macOS and FreeBSD on our build hosts, but I could not test the actual functionality. Could you verify that I didn't break anything?

**Comment by sddj** [comment]
I have reviewed the changes and found two small issues.  The loop searching through handlers needs to continue iterating until a matching interface_name is found.  setup_handlers() needs to return FALSE when getifaddrs() fails.  I've attached a patch with fixes.  I successfully tested with these changes.

[2020-01-21.patch.txt](https://github.com/strongswan/strongswan/files/5852785/2020-01-21.patch.txt)

**Comment by tobiasbrunner** [comment]
Great, thanks. I've merged the changes to master.

**Pull request closed without merging**
