### PR TITLE
swanctl: Add --list_conn_reqid command

### PR DESCRIPTION
**Pull request by Ferryworld**
list currently active connection name and reqid map

### CODE REVIEW

**Comment by tobiasbrunner** [comment]
What exactly is the purpose of this command? Why not just use one of the bindings and directly do this via VICI.

**Comment by Ferryworld** [comment]
connection name and reqid mapping is important for fastpath design.
reqid is the keyword to find a special connection in fastpath, then useful information can be located for statistics in communications.

**Comment by tobiasbrunner** [comment]
But I don't really see the point in adding such a specialized command, which only outputs information already available to users via `--list-sas`, to swanctl. And when some kind of automated querying is the goal then you have to parse this output again anyway, when you can much more easily use one of the VICI bindings and integrate this kind of query directly into your application or workflow.

**Comment by Ferryworld** [comment]
Indeed, it is duplicate in the swanctl point of view.
What this request accomplished is to facilitate application.

**Pull request closed without merging**
