### PR TITLE
chore: better log for constraint check failed identity error

### PR DESCRIPTION
**Pull request by flobz**
Hello,
I had hard time to troubleshoot wrong configuration of the right VPN side.
This changes allow me to have better log to fix config error.

### CODE REVIEW

**Comment by tobiasbrunner** [comment]
@cla-bot check

Thanks, I've fixed some code style issues and changed the messages some more. See the _2088-id-mismatch-log_ branch. Please let me know if those changes are OK with you.

**Comment by flobz** [comment]
Hello @tobiasbrunner ,
Thanks for the improvements it looks good to me.

**Comment by flobz** [comment]
I copied your commit in this branch

**Comment by tobiasbrunner** [comment]
> Thanks for the improvements it looks good to me.

Thanks for the review.

> I copied your commit in this branch

That's OK, but wasn't necessary. I've pushed the change to master.

**Pull request closed without merging**
