### PR TITLE
Create charon plugin that adds and removes proxy ARP entries

### PR DESCRIPTION
**Pull request by sddj**
The FARP plugin uses linux specific packet filters and so is not compatible with macos. This plugin adds and removes proxy ARP entries to the host routing as VPN connections go up and down.

### CODE REVIEW

**Comment by tobiasbrunner** [comment]
Thanks for your efforts, but what exactly is the advantage of this plugin over simply calling `arp -s <vip> <ether addr or auto> pub` from a [vici](https://wiki.strongswan.org/projects/strongswan/wiki/Vici) or [updown](https://wiki.strongswan.org/projects/strongswan/wiki/updown) script? Seems like a lot of code to replicate that command. (Note that due to its dynamic nature, the _farp_ plugin has a different scope, it can e.g. proxy ARP for multiple IPs, ranges or even complete remote subnets.) Also, what's the point of the Linux specific code when we can simply use the _farp_ plugin there?

**Comment by sddj** [comment]
Thanks for the review.  You make really good points.  I only added the Linux specific code to get past the CI checks. It was a good exercise for me to learn more about how to build a plugin and get it to work in StrongSwan.  Just thought it might be useful to try to contribute.  Should I close the pull request?

**Comment by tobiasbrunner** [comment]
>  I only added the Linux specific code to get past the CI checks.

Ah, I see. You could have disabled it for those builds and enabled it for the FreeBSD/macOS builds (like we do with e.g. the _kernel-pfroute_ plugin, see [scripts/test.sh](https://github.com/strongswan/strongswan/blob/master/scripts/test.sh)).

>  Just thought it might be useful to try to contribute. Should I close the pull request?

Let me assure you that that's really appreciated.  But I've currently no plans to adopt this plugin. A solution using `arp(8)` and a script could perhaps be documented on our wiki. For instance, on [forwarding and split-tunneling](https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling) or perhaps just on the page for the [farp plugin](https://wiki.strongswan.org/projects/strongswan/wiki/Farpplugin) that's already linked there, or simply as a comment to [issue 3498](https://wiki.strongswan.org/issues/3498) (similar to the snippets in [issue 1008](https://wiki.strongswan.org/issues/1008) for proxy NDP), which could then be linked from the farp plugin page until we manage to port the plugin to BSD-based systems (a note about its incompatibility is missing there anyway).

**Comment by sddj** [comment]
Thanks again for the review.

**Pull request closed without merging**
