### PR TITLE
charon-nm: port to libnm

### PR DESCRIPTION
**Pull request by lkundrak**
libnm-glib is deprecated for several years and reaching the end of its
life. Let's switch to the more up-to-date library.

### CODE REVIEW

**Comment by lkundrak** [comment]
Please note that this might not be ready for merging yet. I basically just compile-tested it, didn't give it any real test.

I eventually plan to do some testing, but I figured out it just might be a good idea to share this early.

**Comment by tobiasbrunner** [comment]
Great, there already is a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862885) for the Debian package concerning this. Looking forward to your update.

**Comment by lkundrak** [comment]
Gave it some testing now.

Worked fine, apart from a hang on connection error -- the disconnect() method is now called on failure even when the plugin is not yet successfully connected.

I've added a condition in the disconnect() method which effectively restores the previous behaviour, but I'm not familiar with the code base enough to understand why the hang happened. Given the behaviour is same as previously, I guess that shouldn't be considered a blocker.

**Comment by tobiasbrunner** [comment]
> Worked fine, apart from a hang on connection error -- the disconnect() method is now called on failure even when the plugin is not yet successfully connected.

When exactly is it called (i.e. what triggers it)? If it's triggered via e.g. `ike_state_change()` and `signal_failure()` then this could create a deadlock if the SA is still checked out and can't again by `disconnect()` (e.g. if any of the calls in `signal_failure()` are blocking until `disconnect()` returns). If that's the problem we could perhaps queue a job that does what `signal_failure()` does in a different thread so the caller can release the SA.

**Comment by lkundrak** [comment]
> When exactly is it called (i.e. what triggers it)? If it's triggered via e.g. ike_state_change() and signal_failure() then this could create a deadlock if the SA is still checked out and can't again by disconnect() (e.g. if any of the calls in signal_failure() are blocking until disconnect() returns). If that's the problem we could perhaps queue a job that does what signal_failure() does in a different thread so the caller can release the SA.

Yes, that's indeed the case.

I've modified the patch to enqueue the actual disconnection and it works well now.

**Comment by tobiasbrunner** [comment]
Great, thanks. I've pushed this to the _nm-charon-libnm_ branch. Can `disconnect()` be called multiple times? Even then, I guess `disconnect_id` is not strictly necessary. Calling `do_disconnect()` multiple times should not be a problem as the calls are queued to the main loop i.e. they will run sequentially and `terminate_ike()` will actually block until the IKE_SA is terminated, i.e. should there be a second call the SA will simply not found anymore, and since `disconnect_id` is reset early before calling `terminate_ike` that might also happen with the current code (unless the `disconnect()` calls happen in quick succession before any of them run).

**Comment by lkundrak** [comment]
> I guess disconnect_id is not strictly necessary.

Correct, not necessary. I thought makes the a bit more idiomatic while potentially avoiding extra work. I'm not sure if you're asking me to remove it, but I don't mind removing it.

**Comment by tobiasbrunner** [comment]
Applied to master. Thanks again!

**Pull request closed without merging**
