### PR TITLE
openssl: Use ECDH_compute_key() for 'x-coordinate only' setting

### PR DESCRIPTION
**Pull request by mahantesh-nvidia**
* ECDH_compute_key() was not used because it only gives
  x-coordinate of the result. However, the default setting,
  as per the errata mentioned, is to use x-coordinate only.
  Use ECDH_compute_key() for this setting as it additionally
  allows hw offload of the computation using dynamic engine
  feature in OpenSSL.
  EC_POINT_mul() doesn't allow hw offload.

Signed-off-by: Mahantesh Salimath <mahantesh@nvidia.com>

### CODE REVIEW

**Comment by tobiasbrunner** [comment]
Thanks. Note that `ECDH_compute_key()` is deprecated and will apparently be removed with OpenSSL 3.0. So this whole thing will have to be refactored to use the EVP interface. For now, I pushed the commit, with some changes (like error handling), to the _gh186-openssl-ecp_ branch and will try to work on refactoring this to the EVP interface. I also don't think the _ecp_x_coordinate_only_ option is still necessary, so I'll remove that too.

**Comment by tobiasbrunner** [comment]
I pushed additional commits to the branch to refactor this (mostly) to the EVP interface. Let me know if this still works with HW offloading.

**Comment by mahantesh-nvidia** [comment]
Thanks @tobiasbrunner , I tested with your additional commits and it still works with HW offloading.

**Comment by tobiasbrunner** [comment]
OK, thanks for testing. I'll close the PR once I merge the branch.

**Pull request closed without merging**
